from torch.nn import (
    AvgPool1d,
    AvgPool2d,
    AvgPool3d,
    MaxPool1d,
    MaxPool2d,
    MaxPool3d,
    MaxUnpool1d,
    MaxUnpool2d,
    MaxUnpool3d,
    FractionalMaxPool2d,
    FractionalMaxPool3d,
    LPPool1d, LPPool2d,
    AdaptiveMaxPool1d,
    AdaptiveMaxPool2d,
    AdaptiveMaxPool3d,
    AdaptiveAvgPool1d,
    AdaptiveAvgPool2d,
    AdaptiveAvgPool3d
)

available_pooling = {
    "AvgPool1d": AvgPool1d,
    "AvgPool2d": AvgPool2d,
    "AvgPool3d": AvgPool3d,
    "MaxPool1d": MaxPool1d,
    "MaxPool2d": MaxPool2d,
    "MaxPool3d": MaxPool3d,
    "MaxUnpool1d": MaxUnpool1d,
    "MaxUnpool2d": MaxUnpool2d,
    "MaxUnpool3d": MaxUnpool3d,
    "FractionalMaxPool2d": FractionalMaxPool2d,
    "FractionalMaxPool3d": FractionalMaxPool3d,
    "LPPool1d": LPPool1d,
    "LPPool2d": LPPool2d,
    "AdaptiveMaxPool1d": AdaptiveMaxPool1d,
    "AdaptiveMaxPool2d": AdaptiveMaxPool2d,
    "AdaptiveMaxPool3d": AdaptiveMaxPool3d,
    "AdaptiveAvgPool1d": AdaptiveAvgPool1d,
    "AdaptiveAvgPool2d": AdaptiveAvgPool2d,
    "AdaptiveAvgPool3d": AdaptiveAvgPool3d
}
