scenarios:
    - name: test_init_with_shape
      desc: Test model with some common input size 224, 299, 512, 1024
      argnames:
        - model_name
      argvals:
        - [alexnet]
        - [googlenet]
        - [convnext_base]
        - [convnext_tiny]
        - [convnext_small]
        - [convnext_large]
        - [densenet121]
        - [densenet161]
        - [densenet169]
        - [densenet201]
        - [efficientnet_b0]
        - [efficientnet_b1]
        - [efficientnet_b2]
        - [efficientnet_b3]
        - [efficientnet_b4]
        - [efficientnet_b5]
        - [efficientnet_b6]
        - [efficientnet_b7]
        - [efficientnet_v2_s]
        - [efficientnet_v2_m]
        - [efficientnet_v2_l]
        - [inception_v3]
        - [mnasnet0_5]
        - [mnasnet0_75]
        - [mnasnet1_0]
        - [mnasnet1_3]
        - [mobilenet_v2]
        - [mobilenet_v3_small]
        - [mobilenet_v3_large]
        - [regnet_y_400mf]
        - [regnet_y_800mf]
        - [regnet_y_1_6gf]
        - [regnet_y_3_2gf]
        - [regnet_y_8gf]
        - [regnet_y_16gf]
        - [regnet_y_32gf]
        - [regnet_y_128gf]
        - [regnet_x_400mf]
        - [regnet_x_800mf]
        - [regnet_x_1_6gf]
        - [regnet_x_3_2gf]
        - [regnet_x_8gf]
        - [regnet_x_16gf]
        - [regnet_x_32gf]
        - [resnet18]
        - [resnet34]
        - [resnet50]
        - [resnet101]
        - [resnet152]
        - [resnext50_32x4d]
        - [resnext101_32x8d]
        - [resnext101_64x4d]
        - [wide_resnet50_2]
        - [wide_resnet101_2]
        - [shufflenet_v2_x0_5]
        - [shufflenet_v2_x1_0]
        - [shufflenet_v2_x1_5]
        - [shufflenet_v2_x2_0]
        - [squeezenet1_0]
        - [squeezenet1_1]
        - [vgg11]
        - [vgg11_bn]
        - [vgg13]
        - [vgg13_bn]
        - [vgg16]
        - [vgg16_bn]
        - [vgg19]
        - [vgg19_bn]
        - [vit_b_16]
        - [vit_b_32]
        - [vit_l_16]
        - [vit_l_32]
        - [vit_h_14]
        - [swin_t]
        - [swin_s]
        - [swin_b]
        - [swin_v2_t]
        - [swin_v2_s]
        - [swin_v2_b]
        - [maxvit_t]


    - name: test_init_with_num_classes
      desc: Test model with fixed input shape and different num_classes (1, 2, 1000)
      argnames:
        - model_name
        - input_shape
      argvals:
        - [alexnet, [3, 224, 224]]
        - [googlenet, [3, 224, 224]]
        - [convnext_base, [3, 224, 224]]
        - [convnext_tiny, [3, 224, 224]]
        - [convnext_small, [3, 224, 224]]
        - [convnext_large, [3, 224, 224]]
        - [densenet121, [3, 224, 224]]
        - [densenet161, [3, 224, 224]]
        - [densenet169, [3, 224, 224]]
        - [densenet201, [3, 224, 224]]
        - [efficientnet_b0, [3, 224, 224]]
        - [efficientnet_b1, [3, 224, 224]]
        - [efficientnet_b2, [3, 224, 224]]
        - [efficientnet_b3, [3, 224, 224]]
        - [efficientnet_b4, [3, 224, 224]]
        - [efficientnet_b5, [3, 224, 224]]
        - [efficientnet_b6, [3, 224, 224]]
        - [efficientnet_b7, [3, 224, 224]]
        - [efficientnet_v2_s, [3, 224, 224]]
        - [efficientnet_v2_m, [3, 224, 224]]
        - [efficientnet_v2_l, [3, 224, 224]]
        - [inception_v3, [3, 224, 224]]
        - [mnasnet0_5, [3, 224, 224]]
        - [mnasnet0_75, [3, 224, 224]]
        - [mnasnet1_0, [3, 224, 224]]
        - [mnasnet1_3, [3, 224, 224]]
        - [mobilenet_v2, [3, 224, 224]]
        - [mobilenet_v3_small, [3, 224, 224]]
        - [mobilenet_v3_large, [3, 224, 224]]
        - [regnet_y_400mf, [3, 224, 224]]
        - [regnet_y_800mf, [3, 224, 224]]
        - [regnet_y_1_6gf, [3, 224, 224]]
        - [regnet_y_3_2gf, [3, 224, 224]]
        - [regnet_y_8gf, [3, 224, 224]]
        - [regnet_y_16gf, [3, 224, 224]]
        - [regnet_y_32gf, [3, 224, 224]]
        - [regnet_y_128gf, [3, 224, 224]]
        - [regnet_x_400mf, [3, 224, 224]]
        - [regnet_x_800mf, [3, 224, 224]]
        - [regnet_x_1_6gf, [3, 224, 224]]
        - [regnet_x_3_2gf, [3, 224, 224]]
        - [regnet_x_8gf, [3, 224, 224]]
        - [regnet_x_16gf, [3, 224, 224]]
        - [regnet_x_32gf, [3, 224, 224]]
        - [resnet18, [3, 224, 224]]
        - [resnet34, [3, 224, 224]]
        - [resnet50, [3, 224, 224]]
        - [resnet101, [3, 224, 224]]
        - [resnet152, [3, 224, 224]]
        - [resnext50_32x4d, [3, 224, 224]]
        - [resnext101_32x8d, [3, 224, 224]]
        - [resnext101_64x4d, [3, 224, 224]]
        - [wide_resnet50_2, [3, 224, 224]]
        - [wide_resnet101_2, [3, 224, 224]]
        - [shufflenet_v2_x0_5, [3, 224, 224]]
        - [shufflenet_v2_x1_0, [3, 224, 224]]
        - [shufflenet_v2_x1_5, [3, 224, 224]]
        - [shufflenet_v2_x2_0, [3, 224, 224]]
        - [squeezenet1_0, [3, 224, 224]]
        - [squeezenet1_1, [3, 224, 224]]
        - [vgg11, [3, 224, 224]]
        - [vgg11_bn, [3, 224, 224]]
        - [vgg13, [3, 224, 224]]
        - [vgg13_bn, [3, 224, 224]]
        - [vgg16, [3, 224, 224]]
        - [vgg16_bn, [3, 224, 224]]
        - [vgg19, [3, 224, 224]]
        - [vgg19_bn, [3, 224, 224]]
        - [vit_b_16, [3, 224, 224]]
        - [vit_b_32, [3, 224, 224]]
        - [vit_l_16, [3, 224, 224]]
        - [vit_l_32, [3, 224, 224]]
        - [vit_h_14, [3, 224, 224]]
        - [swin_t, [3, 224, 224]]
        - [swin_s, [3, 224, 224]]
        - [swin_b, [3, 224, 224]]
        - [swin_v2_t, [3, 224, 224]]
        - [swin_v2_s, [3, 224, 224]]
        - [swin_v2_b, [3, 224, 224]]
        - [maxvit_t, [3, 224, 224]]


    - name: test_init_with_pretrained_weight_and_default_new_head
      argnames:
        - model_name
        - pretrained_weight
      argvals:
        - [alexnet, true]
        - [googlenet, true]
        - [convnext_base, true]
        - [convnext_tiny, true]
        - [convnext_small, true]
        - [convnext_large, true]
        - [densenet121, true]
        - [densenet161, true]
        - [densenet169, true]
        - [densenet201, true]
        - [efficientnet_b0, true]
        - [efficientnet_b1, true]
        - [efficientnet_b2, true]
        - [efficientnet_b3, true]
        - [efficientnet_b4, true]
        - [efficientnet_b5, true]
        - [efficientnet_b6, true]
        - [efficientnet_b7, true]
        - [efficientnet_v2_s, true]
        - [efficientnet_v2_m, true]
        - [efficientnet_v2_l, true]
        - [inception_v3, true]
        - [mnasnet0_5, true]
        - [mnasnet0_75, true]
        - [mnasnet1_0, true]
        - [mnasnet1_3, true]
        - [mobilenet_v2, true]
        - [mobilenet_v3_small, true]
        - [mobilenet_v3_large, true]
        - [regnet_y_400mf, true]
        - [regnet_y_800mf, true]
        - [regnet_y_1_6gf, true]
        - [regnet_y_3_2gf, true]
        - [regnet_y_8gf, true]
        - [regnet_y_16gf, true]
        - [regnet_y_32gf, true]
        - [regnet_y_128gf, true]
        - [regnet_x_400mf, true]
        - [regnet_x_800mf, true]
        - [regnet_x_1_6gf, true]
        - [regnet_x_3_2gf, true]
        - [regnet_x_8gf, true]
        - [regnet_x_16gf, true]
        - [regnet_x_32gf, true]
        - [resnet18, true]
        - [resnet34, true]
        - [resnet50, true]
        - [resnet101, true]
        - [resnet152, true]
        - [resnext50_32x4d, true]
        - [resnext101_32x8d, true]
        - [resnext101_64x4d, true]
        - [wide_resnet50_2, true]
        - [wide_resnet101_2, true]
        - [shufflenet_v2_x0_5, true]
        - [shufflenet_v2_x1_0, true]
        - [shufflenet_v2_x1_5, true]
        - [shufflenet_v2_x2_0, true]
        - [squeezenet1_0, true]
        - [squeezenet1_1, true]
        - [vgg11, true]
        - [vgg11_bn, true]
        - [vgg13, true]
        - [vgg13_bn, true]
        - [vgg16, true]
        - [vgg16_bn, true]
        - [vgg19, true]
        - [vgg19_bn, true]
        - [vit_b_16, true]
        - [vit_b_32, true]
        - [vit_l_16, true]
        - [vit_l_32, true]
        - [vit_h_14, true]
        - [swin_t, true]
        - [swin_s, true]
        - [swin_b, true]
        - [swin_v2_t, true]
        - [swin_v2_s, true]
        - [swin_v2_b, true]
        - [maxvit_t, true]
